// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class City
    {
        public City()
        {
            Districts = new HashSet<District>();
        }

        public int CityId { get; set; }
        public string CityName { get; set; }

        public virtual ICollection<District> Districts { get; set; }
    }
}