// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class EvaluationInput
    {
        public string MerchandiseName { get; set; }
        public int MerchandiseId { get; set; }
        public string SpecName { get; set; }
        public int OrderId { get; set; }
        public int SpecId { get; set; }
        public int EvaluationId { get; set; }
        public string Comment { get; set; }
        public int Score { get; set; }
    }
}