// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class ManuallyWeightedEntry
    {
        public int EntryId { get; set; }
        public int? TagId { get; set; }
        public int? MerchandiseId { get; set; }
        public int? SpecId { get; set; }
        public int Weight { get; set; }

        public virtual Merchandise Merchandise { get; set; }
        public virtual Spec Spec { get; set; }
        public virtual Tag Tag { get; set; }
    }
}