// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class Merchandise
    {
        public Merchandise()
        {
            Evaluations = new HashSet<Evaluation>();
            ManuallyWeightedEntries = new HashSet<ManuallyWeightedEntry>();
            Specs = new HashSet<Spec>();
        }

        public int MerchandiseId { get; set; }
        public string MerchandiseName { get; set; }
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public bool Display { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<ManuallyWeightedEntry> ManuallyWeightedEntries { get; set; }
        public virtual ICollection<Spec> Specs { get; set; }
    }
}