// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class Order
    {
        public Order()
        {
            Evaluations = new HashSet<Evaluation>();
            OrderLists = new HashSet<OrderList>();
        }

        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public int PaymentMethodId { get; set; }
        public bool Payed { get; set; }
        public DateTime PurchaseTime { get; set; }
        public int? UsedCouponId { get; set; }
        public int? PaymentAmount { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryDistrict { get; set; }
        public string DeliveryAddress { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string Remark { get; set; }

        public virtual Member Member { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<OrderList> OrderLists { get; set; }
    }
}