// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class OrderList
    {
        public int OrderListId { get; set; }
        public int OrderId { get; set; }
        public int SpecId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }

        public virtual Order Order { get; set; }
        public virtual Spec Spec { get; set; }
    }
}