// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class RatingData
    {
        public int EvaluationWeight { get; set; }
        public int PurchasedWeight { get; set; }
        public int ManuallyWeight { get; set; }
        public int RateEvaluationFunc { get; set; }
        public int RatePurchaseFunc { get; set; }
        public int? RecentEvaluationDays { get; set; }
        public int? RecentEvaluationTimes { get; set; }
        public int? RecentPurchasedDays { get; set; }
        public int? RecentPurchasedTimes { get; set; }
    }
}