// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class Spec
    {
        public Spec()
        {
            CartItems = new HashSet<CartItem>();
            Evaluations = new HashSet<Evaluation>();
            ManuallyWeightedEntries = new HashSet<ManuallyWeightedEntry>();
            OrderLists = new HashSet<OrderList>();
        }

        public int SpecId { get; set; }
        public string SpecName { get; set; }
        public int MerchandiseId { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public string ImageUrl { get; set; }
        public int DiscountPercentage { get; set; }
        public int DisplayOrder { get; set; }
        public double Popularity { get; set; }
        public bool OnShelf { get; set; }

        public virtual Merchandise Merchandise { get; set; }
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<ManuallyWeightedEntry> ManuallyWeightedEntries { get; set; }
        public virtual ICollection<OrderList> OrderLists { get; set; }
    }
}