// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class SpecDisplayforOrder
    {
        public int SpecId { get; set; }
        public string BrandName { get; set; }
        public string CategoryName { get; set; }
        public string FullName { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public int DiscountPercentage { get; set; }
        public bool OnShelf { get; set; }
        public int DisplayOrder { get; set; }
    }
}