// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class Tag
    {
        public Tag()
        {
            ManuallyWeightedEntries = new HashSet<ManuallyWeightedEntry>();
        }

        public int TagId { get; set; }
        public string TagName { get; set; }

        public virtual ICollection<ManuallyWeightedEntry> ManuallyWeightedEntries { get; set; }
    }
}